using Yuebon.Commons.Attributes;

namespace Yuebon.Security.SeedData;

public class ItemsDetailSeedData:SeedDataEntity
{
    /// <summary>
    /// 种子数据
    /// </summary>
    /// <returns></returns>
    [IgnoreUpdate]
    public IEnumerable<ItemsDetail> HasData()
    {
        return new[] {
            new ItemsDetail{
                Id= 9165817405374533,
                ItemId= 9165809527554117,
                ParentId= 0,
                ItemCode= "Group",
                ItemName= "集团",
                IsDefault= false,
                Layers= null,
                SortCode= 99,
                DeleteMark= false,
                EnabledMark= true,
                CreatorTime= DateTime.Now,
                CreatorUserId = 9165855286886368,
                LastModifyTime= null,
                LastModifyUserId= null,
                DeleteTime= null,
                DeleteUserId= null
            },
            new ItemsDetail{
                Id= 9165836811632709,
                ItemId= 9165809527554117,
                ParentId= 0,
                ItemCode= "Company",
                ItemName= "公司",
                IsDefault= false,
                Layers= null,
                SortCode= 99,
                DeleteMark= false,
                EnabledMark= true,
                CreatorTime= DateTime.Now,
                CreatorUserId = 9165855286886368,
                LastModifyTime= null,
                LastModifyUserId= null,
                DeleteTime= null,
                DeleteUserId= null
            },
            new ItemsDetail{
                Id= 9165850199064645,
                ItemId= 9165809527554117,
                ParentId= 0,
                ItemCode= "SubCompany",
                ItemName= "子公司",
                SimpleSpelling= null,
                IsDefault= false,
                Layers= null,
                SortCode= 99,
                DeleteMark= false,
                EnabledMark= true,
                CreatorTime= DateTime.Now,
                CreatorUserId = 9165855286886368,
                LastModifyTime= null,
                LastModifyUserId= null,
                DeleteTime= null,
                DeleteUserId= null
            },
            new ItemsDetail{
                Id= 9165852817752133,
                ItemId= 9165809527554117,
                ParentId= 0,
                ItemCode= "Department",
                ItemName= "部门",
                IsDefault= false,
                Layers= null,
                SortCode= 99,
                DeleteMark= false,
                EnabledMark= true,
                CreatorTime= DateTime.Now,
                CreatorUserId = 9165855286886368,
                LastModifyTime= null,
                LastModifyUserId= null,
                DeleteTime= null,
                DeleteUserId= null
            },
            new ItemsDetail{
                Id= 9165855286886469,
                ItemId= 9165809527554117,
                ParentId= 0,
                ItemCode= "WorkGroup",
                ItemName= "小组",
                IsDefault= false,
                Layers= null,
                SortCode= 99,
                DeleteMark= false,
                EnabledMark= true,
                CreatorTime= DateTime.Now,
                CreatorUserId = 9165855286886368,
                LastModifyTime= null,
                LastModifyUserId= null,
                DeleteTime= null,
                DeleteUserId= null
            },
            new ItemsDetail{
                Id= 14224299715445,
                ItemId= 9165813031108677,
                ParentId= 0,
                ItemCode= "0",
                ItemName= "全局",
                SimpleSpelling= null,
                IsDefault= false,
                Layers= null,
                SortCode= 99,
                DeleteMark= false,
                EnabledMark= true,
                CreatorTime= DateTime.Now,
                CreatorUserId = 9165855286886368,
                LastModifyTime= null,
                LastModifyUserId= null,
                DeleteTime= null,
                DeleteUserId= null
            },
            new ItemsDetail{
                Id= 9165857562951749,
                ItemId= 9165813031108677,
                ParentId= 0,
                ItemCode= "1",
                ItemName= "系统角色",
                SimpleSpelling= null,
                IsDefault= false,
                Layers= null,
                SortCode= 99,
                DeleteMark= false,
                EnabledMark= true,
                CreatorTime= DateTime.Now,
                CreatorUserId = 9165855286886368,
                LastModifyTime= null,
                LastModifyUserId= null,
                DeleteTime= null,
                DeleteUserId= null
            },
            new ItemsDetail{
                Id= 9165859013525573,
                ItemId= 9165813031108677,
                ParentId= 0,
                ItemCode= "2",
                ItemName= "业务角色",
                IsDefault= false,
                Layers= null,
                SortCode= 99,
                DeleteMark= false,
                EnabledMark= true,
                CreatorTime= DateTime.Now,
                CreatorUserId = 9165855286886368,
                LastModifyTime= null,
                LastModifyUserId= null,
                DeleteTime= null,
                DeleteUserId= null
            },
            new ItemsDetail{
                Id= 9165860710645829,
                ItemId= 9165813031108677,
                ParentId= 0,
                ItemCode= "3",
                ItemName= "其他角色",
                SimpleSpelling= null,
                IsDefault= false,
                Layers= null,
                SortCode= 99,
                DeleteMark= false,
                EnabledMark= true,
                CreatorTime= DateTime.Now,
                CreatorUserId = 9165855286886368,
                LastModifyTime= null,
                LastModifyUserId= null,
                DeleteTime= null,
                DeleteUserId= null
            },
            new ItemsDetail{
                Id= 14784953439617093,
                ItemId= 14784931925590085,
                ParentId= 0,
                ItemCode= "SysOrg",
                ItemName= "系统组织",
                SimpleSpelling= null,
                IsDefault= false,
                Layers= null,
                SortCode= 99,
                DeleteMark= false,
                EnabledMark= true,
                CreatorTime= DateTime.Now,
                CreatorUserId = 9165855286886368,
                LastModifyTime= null,
                LastModifyUserId= null,
                DeleteTime= null,
                DeleteUserId= null
            },
            new ItemsDetail{
                Id= 14784959590694982,
                ItemId= 14784931925590085,
                ParentId= 0,
                ItemCode= "BusinessOrg",
                ItemName= "业务组织",
                SimpleSpelling= null,
                IsDefault= false,
                Layers= null,
                SortCode= 99,
                DeleteMark= false,
                EnabledMark= true,
                CreatorTime= DateTime.Now,
                CreatorUserId = 9165855286886368,
                LastModifyTime= null,
                LastModifyUserId= null,
                DeleteTime= null,
                DeleteUserId= null
            },
            new ItemsDetail{
                Id= 14784959590694983,
                ItemId= 14784931925590085,
                ParentId= 0,
                ItemCode= "ThreeOrg",
                ItemName= "第三方组织",
                SimpleSpelling= null,
                IsDefault= false,
                Layers= null,
                SortCode= 99,
                DeleteMark= false,
                EnabledMark= true,
                CreatorTime= DateTime.Now,
                CreatorUserId = 9165855286886368,
                LastModifyTime= null,
                LastModifyUserId= null,
                DeleteTime= null,
                DeleteUserId= null
            }
        };
    }
}
